In [10]:
import duckdb
import os
import pandas as pd

def get_match_events(match_id):
    path = os.path.expanduser(f"~/projects/statsbomb-data/data/events/{match_id}.json")
    query = f"""
    SELECT
        {match_id} AS match_id,
        id,
        index,
        minute,
        second,
        timestamp,
        type.name AS type,
        possession,
        play_pattern.name AS play_pattern,
        team.name AS team,
        player.id AS player_id,
        player.name AS player_name,
        position.name AS position,
        location[1] AS x,
        location[2] AS y,
        duration,
        under_pressure
    FROM read_json_auto('{path}')
    ORDER BY index
    """
    return duckdb.sql(query).df()

test = get_match_events(3754217)
print(test.shape)
test.head()

(3732, 17)

,match_id,id,index,minute,second,timestamp,type,possession,play_pattern,team,player_id,player_name,position,x,y,duration,under_pressure
0,3754217,9d86a178-3514-45d1-9d14-1372e846d17b,1,0,0,00:00:00,Starting XI,1,Regular Play,Chelsea,<NA>,NaN,NaN,NaN,NaN,0.000000,<NA>
1,3754217,82acc213-90f3-4fee-8305-bd9e403cec42,2,0,0,00:00:00,Starting XI,1,Regular Play,Arsenal,<NA>,NaN,NaN,NaN,NaN,0.000000,<NA>
2,3754217,d18f1a33-65ba-42e5-a9fd-bbfc709694e8,3,0,0,00:00:00,Half Start,1,Regular Play,Chelsea,<NA>,NaN,NaN,NaN,NaN,0.000000,<NA>
3,3754217,49147091-455c-4372-8d56-96e1ca71d01a,4,0,0,00:00:00,Half Start,1,Regular Play,Arsenal,<NA>,NaN,NaN,NaN,NaN,0.000000,<NA>
4,3754217,5f9bdb6d-0379-4f42-9f53-29777f166db5,5,0,0,00:00:00.622000,Pass,2,From Kick Off,Arsenal,3668,Theo Walcott,Center Forward,61.0,40.1,0.386674,<NA>

In [11]:
test = get_match_events(3754217)
print(test.shape)
test.head()

(3732, 17)

,match_id,id,index,minute,second,timestamp,type,possession,play_pattern,team,player_id,player_name,position,x,y,duration,under_pressure
0,3754217,9d86a178-3514-45d1-9d14-1372e846d17b,1,0,0,00:00:00,Starting XI,1,Regular Play,Chelsea,<NA>,NaN,NaN,NaN,NaN,0.000000,<NA>
1,3754217,82acc213-90f3-4fee-8305-bd9e403cec42,2,0,0,00:00:00,Starting XI,1,Regular Play,Arsenal,<NA>,NaN,NaN,NaN,NaN,0.000000,<NA>
2,3754217,d18f1a33-65ba-42e5-a9fd-bbfc709694e8,3,0,0,00:00:00,Half Start,1,Regular Play,Chelsea,<NA>,NaN,NaN,NaN,NaN,0.000000,<NA>
3,3754217,49147091-455c-4372-8d56-96e1ca71d01a,4,0,0,00:00:00,Half Start,1,Regular Play,Arsenal,<NA>,NaN,NaN,NaN,NaN,0.000000,<NA>
4,3754217,5f9bdb6d-0379-4f42-9f53-29777f166db5,5,0,0,00:00:00.622000,Pass,2,From Kick Off,Arsenal,3668,Theo Walcott,Center Forward,61.0,40.1,0.386674,<NA>